# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c55c3a4e7388d7d8e5404129f31d9855960b2df8fe15cdbc628bd8d8695fcb80f08eee639aab0e4fb65969cc4ea4e88b635cc0eeea07011a2829e3c9dcffad71

test:
  secret_key_base: a975b37871421605929aa154514cc2272d80eea87cf6722c0b34952caae30eff0800abdf5f53b8b31c74140c64fba71602756c25a9cf5cfcba516da5277908a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
